# Generated by Django 5.2.7 on 2025-12-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='SecureVote Blockchain', max_length=255)),
                ('groq_api_key', models.CharField(blank=True, help_text='Enter GROQ API Key here to override environment variable', max_length=255, null=True)),
                ('admin_primary_color', models.CharField(default='#0f172a', max_length=20)),
                ('admin_secondary_color', models.CharField(default='#1e293b', max_length=20)),
                ('voter_primary_color', models.CharField(default='#064e3b', max_length=20)),
                ('voter_secondary_color', models.CharField(default='#065f46', max_length=20)),
                ('candidate_primary_color', models.CharField(default='#7c2d12', max_length=20)),
                ('candidate_secondary_color', models.CharField(default='#9a3412', max_length=20)),
                ('maintenance_mode', models.BooleanField(default=False, help_text='If active, only Superadmin can access the site')),
                ('allow_registration', models.BooleanField(default=True, help_text='Allow new users to register')),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
