# Generated by Django 5.2.7 on 2025-12-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_siteconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='system_load_percentage',
            field=models.IntegerField(default=12, help_text='Percentage (0-100) to display in System Load'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='voter_participation_rate',
            field=models.IntegerField(default=45, help_text='Percentage (0-100) to display in Election Health'),
        ),
    ]
