# Generated by Django 5.2.7 on 2025-12-14 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_siteconfiguration_system_load_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='security_encryption_active',
            field=models.BooleanField(default=False, help_text='Global switch for the Security Indicator Box'),
        ),
    ]
