# Generated by Django 5.2.7 on 2025-12-14 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_siteconfiguration_security_encryption_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Upload a custom favicon (PNG/ICO)', null=True, upload_to='favicons/'),
        ),
    ]
