# Generated by Django 5.2.7 on 2025-12-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
