# Generated by Django 5.2.7 on 2025-12-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_candidate_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='symbol',
            field=models.CharField(default='👤', max_length=10),
        ),
    ]
